import { createApp } from 'vue';
import './style/index.scss';
import App from './App.vue';
import router from './router';
import 'virtual:svg-icons-register';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import pinia from './store';
import PageTool from '@/components/PageTool/index.vue';
const app = createApp(App);
app.component('PageTool', PageTool);
app.use(router).use(pinia).use(ElementPlus).mount('#app');
